[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
check_untyped_defs = true
ignore_missing_imports = true
no_warn_no_return = true

[[tool.mypy.overrides]]
module = "queuelib.tests.*"
allow_untyped_defs = true
allow_untyped_calls = true
check_untyped_defs = false

[tool.black]
target-version = ["py38", "py39", "py310", "py311", "py312"]