[tox]
envlist = py, pylint, mypy, twinecheck, pre-commit

[testenv]
deps =
    pytest
    pytest-cov >= 7.0.0
commands =
    py.test --cov=queuelib --cov-report=xml --cov-report=term-missing \
        --junitxml=testenv.junit.xml -o junit_family=legacy \
        {posargs:queuelib}

[testenv:pylint]
basepython = python3
deps =
    {[testenv]deps}
    pylint==4.0.7
commands =
    pylint {posargs:queuelib}

[testenv:mypy]
basepython = python3
deps =
    mypy==2.3.1
    pytest==9.1.1
commands =
    mypy {posargs:queuelib}

[testenv:twinecheck]
basepython = python3
deps =
    twine==7.0.0
    build==1.5.0
commands =
    python -m build --sdist
    twine check dist/*

[testenv:pre-commit]
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure
skip_install = true
