name: Checks
on: [push, pull_request]

jobs:
  checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
        - python-version: 3
          env:
            TOXENV: black
        - python-version: 3
          env:
            TOXENV: flake8
        - python-version: 3
          env:
            TOXENV: pylint
        - python-version: 3
          env:
            TOXENV: security
        - python-version: 3
          env:
            TOXENV: typing

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run check
      env: ${{ matrix.env }}
      run: |
        pip install -U pip
        pip install -U tox
        tox
