name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Build
      run: | 
        pip install --upgrade build twine
        python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@v1.10.3
      with:
        password: ${{ secrets.PYPI_TOKEN }}
